// <auto-generated />
using EFCoreRetailStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreRetailStore.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    partial class RetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreRetailStore.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Electronics",
                            Price = 50000m,
                            ProductName = "Laptop",
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Electronics",
                            Price = 25000m,
                            ProductName = "Mobile",
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Electronics",
                            Price = 30000m,
                            ProductName = "Tablet",
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Accessories",
                            Price = 1200m,
                            ProductName = "Keyboard",
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Accessories",
                            Price = 800m,
                            ProductName = "Mouse",
                            Quantity = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
